const MAP_HTML = [
  '<!DOCTYPE html><html><head>',
  '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">',
  '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />',
  '<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>',
  '<style>',
    '*{margin:0;padding:0;box-sizing:border-box}',
    'body{font-family:-apple-system,sans-serif;overflow:hidden}',
    '#map{width:100vw;height:100vh}',
    '.dog-marker{width:36px;height:36px;border-radius:50%;display:flex;align-items:center;justify-content:center;border:3px solid #fff;box-shadow:0 2px 8px rgba(0,0,0,.3);font-size:18px;cursor:pointer}',
    '.custom-popup .leaflet-popup-content-wrapper{border-radius:16px;box-shadow:0 4px 20px rgba(0,0,0,.15);padding:4px}',
    '.custom-popup .leaflet-popup-content{margin:8px 12px;font-size:14px;min-width:150px}',
    '.popup-name{font-weight:800;font-size:16px;color:#333}',
    '.popup-raza{color:#666;font-size:13px;margin-top:2px}',
    '.popup-row{display:flex;gap:8px;margin-top:6px}',
    '.popup-badge{background:#C4622D;color:#fff;border-radius:8px;padding:2px 8px;font-size:11px;font-weight:700}',
    '.popup-dist{color:#888;font-size:11px}',
    '.user-marker{width:20px;height:20px;border-radius:50%;background:#4285F4;border:3px solid #fff;box-shadow:0 0 0 3px rgba(66,133,244,.3)}',
    '.user-pulse{width:40px;height:40px;border-radius:50%;background:rgba(66,133,244,.15);position:absolute;top:-10px;left:-10px;animation:pulse 2s infinite}',
    '@keyframes pulse{0%{transform:scale(.8);opacity:.5}100%{transform:scale(1.5);opacity:0}}',
  '</style></head><body><div id="map"></div><script>',
    'var C={jugar:"#4CAF50",pasear:"#2196F3",reproduccion:"#E91E63",todo:"#FF9800"};',
    'var Lb={jugar:"Jugar",pasear:"Pasear",reproduccion:"Reproducci\u00f3n",todo:"Todo"};',
    'var map,ds=[];',
    'function init(lat,lng,ps){',
      'map=L.map("map",{center:[lat,lng],zoom:12,zoomControl:false,attributionControl:false});',
      'L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19}).addTo(map);',
      'L.marker([lat,lng],{icon:L.divIcon({className:"",html:\'<div class="user-marker"><div class="user-pulse"></div></div>\',iconSize:[20,20],iconAnchor:[10,10]}),zIndexOffset:1000}).addTo(map);',
      'addDogs(ps);',
    '}',
    'function addDogs(ps){',
      'ds.forEach(function(m){map.removeLayer(m)});ds=[];',
      'ps.forEach(function(p){',
        'if(!p.latitud||!p.longitud)return;',
        'var c=C[p.proposito]||"#FF9800",lb=Lb[p.proposito]||"Todo";',
        'var mi=L.divIcon({className:"",html:\'<div class="dog-marker" style="background:\'+c+\'">🐾</div>\',iconSize:[36,36],iconAnchor:[18,18]});',
        'var km=p.distancia?p.distancia+" km":"";',
        'var pop=\'<div><div class="popup-name">\'+(p.nombre||"Sin nombre")+\'</div><div class="popup-raza">\'+(p.raza||"Mestizo")+\'</div><div class="popup-row"><span class="popup-badge">🐾 \'+lb+\'</span><span class="popup-dist">\'+km+\'</span></div></div>\';',
        'var m=L.marker([parseFloat(p.latitud),parseFloat(p.longitud)],{icon:mi}).addTo(map);',
        'm.bindPopup(pop,{className:"custom-popup",closeButton:false});',
        'm.on("click",function(){window.ReactNativeWebView&&window.ReactNativeWebView.postMessage(JSON.stringify({type:"dogSelected",dog:p}))});',
        'ds.push(m);',
      '});',
    '}',
    'function center(lat,lng){if(map)map.setView([lat,lng],14,{animate:true})}',
    'window.onmessage=function(e){try{var d=JSON.parse(e.data);if(d.type==="init")init(d.lat,d.lng,d.perros);else if(d.type==="center")center(d.lat,d.lng);else if(d.type==="updateDogs")addDogs(d.perros||[])}catch(e){}};',
  '</script></body></html>',
].join('');
export default MAP_HTML;
